controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

when@dev:
  _errors:
    resource: "@FrameworkBundle/Resources/config/routing/errors.xml"
    prefix: /_error
